---
- name: Show hostname
  hosts: all
  gather_facts: no
  tasks:
    - name: Get the hostname
      command: hostname
      register: result

    - name: Display the hostname
      debug:
        msg: "The hostname is {{ result.stdout }}"
